- hosts: type_t1_micro 

  tasks:
  - debug: msg="item = {{ item }} hostvars = {{ hostvars[item]['ec2_id'] }} "
    with_items: play_hosts
  - debug: msg="static hostvars {{ hostvars['ec2-54-82-200-213.compute-1.amazonaws.com']['ec2_platform'] }} "
  - name: Use ec2_id
    shell: echo {{ hostvars[item]['ec2_id'] }}
    register: uptime
    with_items: play_hosts
  - debug: var=uptime.cmd

  - name: tag a resource
    local_action: ec2_tag resource={{ hostvars[item]['ec2_id'] }} region=us-east-1 state=present
    with_items: play_hosts
    args:
      tags:
        Name: ubervol6
        env: prod
