- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Provision
    ec2: >
       keypair={{mykeypair}}
       group={{security_group}}
       instance_type={{instance_type}}
       image={{image}}
       wait=true
       counter={{number}}
    register: ec2
