---
- name: Install AWS CLI
  hosts: all
  user: ubuntu
  sudo: True

  tasks:
    - name: install pip
      apt: pkg=python-pip state=latest

    - name: Install boto
      pip: name=boto state=latest

    - name: Install AWS CLI
      pip: name=awscli state=latest

    - name: Configure autocomplete
      copy: src=../files/aws dest=/etc/bash_completion.d owner=root group=root mode=0644
